### ISSUE TITLE
Crash during posting

### ISSUE THREAD

**Issue by whatevs** [madcowfred/newsmangler#10] opened 2012-03-11 14:58 UTC
Newsmangler almost always crashes when I try to post. I've tried both freddie and vanilla modules. 

It's not always immediate. I get this report:

Traceback (most recent call last):
File "/home/whatevs/newsmangler/classes/BaseMangler.py", line 91, in poll
obj.handle_read_event()
File "/usr/lib/python2.7/asyncore.py", line 444, in handle_read_event
self.handle_read()
File "/home/whatevs/newsmangler/classes/asyncNNTP.py", line 173, in handle_read
self._readbuf += self.recv(16384)
File "/usr/lib/python2.7/asyncore.py", line 388, in recv
self.handle_close()
File "/home/whatevs/newsmangler/classes/asyncNNTP.py", line 155, in handle_close
self.really_close()
File "/home/whatevs/newsmangler/classes/asyncNNTP.py", line 161, in really_close
self.close()
File "/home/whatevs/newsmangler/classes/asyncNNTP.py", line 103, in close
self.del_channel()
File "/home/whatevs/newsmangler/classes/asyncNNTP.py", line 98, in del_channel
asyncore.poller.unregister(self._fileno)
TypeError: argument must be an int, or have a fileno() method.
2012-03-08 22:21:59,465 [WARNING] Invalid FD for poll() - 8
Traceback (most recent call last):
File "poster.py", line 150, in <module>
main()
File "poster.py", line 145, in main
poster.post(newsgroup, postme, post_title=post_title)
File "/home/whatevs/newsmangler/classes/Poster.py", line 118, in post
_poll()
File "/home/whatevs/newsmangler/classes/BaseMangler.py", line 99, in poll
obj.handle_error()
AttributeError: 'NoneType' object has no attribute 'handle_error'

I'm using Python 2.7.2+ if that makes a difference.

**Comment by madcowfred** [comment] 2012-03-12 04:29
I've just been looking into this one, update and see if you get any sort of useful errors. Ideally post a test directory using "python mangler.py -d testdir" and send me the log (email, pastebin, whatever).

**Comment by madcowfred** [comment] 2012-03-15 04:39
Marking as a dupe of #7

**Closed as completed by madcowfred** 2012-03-15 04:39 UTC
